name: benchmark

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/flekspy/idl/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: |
          uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run benchmark
        run: |
          uv run pytest --benchmark-only --benchmark-json=benchmark.json

      - name: Store benchmark result
        uses: j3hempsey-actions/github-action-benchmark@v1
        with:
          name: Pytest Benchmark
          tool: 'pytest'
          output-file-path: benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          fail-on-alert: true
