name: benchmark

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/flekspy/idl/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: |
          uv python install
          uv pip install pytest-md-report

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run benchmark
        run: |
          uv run pytest --benchmark-only --md-report > benchmark.md

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: find
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "Benchmark Results"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: benchmark.md
          edit-mode: replace
